output "cluster_id" {
  description = "EKS cluster ID"
  value       = module.eks.cluster_id
}

output "cluster_endpoint" {
  description = "Endpoint for EKS control plane"
  value       = module.eks.cluster_endpoint
}

output "cluster_security_group_id" {
  description = "Security group ID attached to the EKS cluster"
  value       = module.eks.cluster_security_group_id
}

output "cluster_iam_role_name" {
  description = "IAM role name associated with EKS cluster"
  value       = module.eks.cluster_iam_role_name
}

output "self_managed_node_groups" {
  description = "Self-managed node groups created"
  value       = module.eks.self_managed_node_groups
}

output "aws_auth_configmap_yaml" {
  description = "Formatted yaml configuration for the aws-auth configmap"
  value       = module.eks.aws_auth_configmap_yaml
}

output "kubectl_config" {
  description = "kubectl config as generated by the module"
  value       = module.eks.kubectl_config
  sensitive   = true
}
